# Generated by Django 5.0.6 on 2024-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_coursedetail_coursefeactures"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefeactures",
            name="course",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.course"
            ),
            preserve_default=False,
        ),
    ]
