# Generated by Django 5.0.6 on 2024-05-13 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_coursedetail_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="blog/")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
