# Generated by Django 5.0.6 on 2024-05-14 05:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
