# Generated by Django 5.0.6 on 2024-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_enquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
        ),
    ]
