# Generated by Django 5.0.6 on 2024-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("qualification", models.CharField(max_length=250)),
                ("resume", models.FileField(upload_to="career/")),
            ],
        ),
    ]
