# Generated by Django 5.0.6 on 2024-05-15 10:17

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_gallery_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("eligibility", "Eligibility"),
                            ("facilities", "Facilities"),
                        ],
                        max_length=200,
                    ),
                ),
                ("description", tinymce.models.HTMLField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.course"
                    ),
                ),
            ],
        ),
    ]
