# Generated by Django 5.0.6 on 2024-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_courseoverview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseoverview",
            name="title",
            field=models.CharField(
                choices=[
                    ("overview", "Overview"),
                    ("training_structure", "Training Structure"),
                    ("eligibility", "Eligibility"),
                    ("facilities", "Facilities"),
                ],
                max_length=200,
            ),
        ),
    ]
