# Generated by Django 5.0.6 on 2024-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_alter_courseoverview_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="students/")),
            ],
        ),
    ]
