# Generated by Django 5.0.6 on 2024-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_expert"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
