# Generated by Django 5.0.6 on 2024-05-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_expert_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={},
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="name",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="order",
        ),
        migrations.AddField(
            model_name="gallery",
            name="images",
            field=models.ImageField(default=1, upload_to="gallery/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="GalleryImage",
        ),
    ]
